name: CI/CD Pipeline (Dev Mode)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          docker-compose exec app npm install
          docker-compose exec app npm test

      - name: Stop containers
        run: docker-compose down
